### ISSUE TITLE
mutSignatures package: error after importing data from MAF files

### ISSUE THREAD

**Issue by pradeep-sidd** [dami82/mutSignatures#19] opened 2023-03-29 17:33 UTC
After multiple attempts, I installed the mutSignatures package and got it to work fine. However, in the middle of the code, I encountered an error while trying to attach the 3-nucleotide context. The message only mentioned that an error had occurred without any other information. I cannot make out where I faltered. I would really appreciate your perspective and help in this matter.

Command

Attach 3-nucleotide context
hg19 <- BSgenome.Hsapiens.UCSC.hg19::BSgenome.Hsapiens.UCSC.hg19

maf.dset.cholangio <- attachContext(mutData = maf.dset.cholangio,
chr_colName = "Chromosome",
start_colName = "Start_Position",
end_colName = "End_position",
nucl_contextN = 3,
BSGenomeDb = hg19)

An error has occurred!

Session info
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22621)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8 LC_CTYPE=English_United States.utf8 LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C LC_TIME=English_United States.utf8

attached base packages:
[1] stats4 stats graphics grDevices utils datasets methods base

other attached packages:
[1] devtools_2.4.5 usethis_2.1.6 rlang_1.1.0
[4] maftools_2.14.0 mutSignatures_2.1.1 foreach_1.5.2
[7] ggplot2_3.4.1 BSgenome.Hsapiens.UCSC.hg19_1.4.3 BSgenome_1.66.3
[10] rtracklayer_1.58.0 Biostrings_2.66.0 XVector_0.38.0
[13] GenomicRanges_1.50.2 GenomeInfoDb_1.34.9 IRanges_2.32.0
[16] S4Vectors_0.36.2 BiocGenerics_0.44.0 BiocManager_1.30.20

loaded via a namespace (and not attached):
[1] bitops_1.0-7 matrixStats_0.63.0 fs_1.6.1 doParallel_1.0.17
[5] RColorBrewer_1.1-3 tools_4.2.2 profvis_0.3.7 utf8_1.2.3
[9] R6_2.5.1 colorspace_2.1-0 urlchecker_1.0.1 DNAcopy_1.72.3
[13] withr_2.5.0 tidyselect_1.2.0 prettyunits_1.1.1 processx_3.8.0
[17] compiler_4.2.2 cli_3.6.1 Biobase_2.58.0 DelayedArray_0.24.0
[21] scales_1.2.1 callr_3.7.3 proxy_0.4-27 stringr_1.5.0
[25] digest_0.6.31 Rsamtools_2.14.0 pkgconfig_2.0.3 htmltools_0.5.5
[29] sessioninfo_1.2.2 MatrixGenerics_1.10.0 fastmap_1.1.1 htmlwidgets_1.6.2
[33] rstudioapi_0.14 shiny_1.7.4 BiocIO_1.8.0 generics_0.1.3
[37] BiocParallel_1.32.6 dplyr_1.1.1 RCurl_1.98-1.12 magrittr_2.0.3
[41] GenomeInfoDbData_1.2.9 Matrix_1.5-3 Rcpp_1.0.10 munsell_0.5.0
[45] fansi_1.0.4 lifecycle_1.0.3 stringi_1.7.12 yaml_2.3.7
[49] SummarizedExperiment_1.28.0 zlibbioc_1.44.0 pkgbuild_1.4.0 grid_4.2.2
[53] parallel_4.2.2 promises_1.2.0.1 crayon_1.5.2 miniUI_0.1.1.1
[57] lattice_0.20-45 splines_4.2.2 ps_1.7.3 pillar_1.9.0
[61] rjson_0.2.21 codetools_0.2-19 pkgload_1.3.2 XML_3.99-0.14
[65] glue_1.6.2 data.table_1.14.8 remotes_2.4.2 vctrs_0.6.1
[69] httpuv_1.6.9 gtable_0.3.3 purrr_1.0.1 cachem_1.0.7
[73] mime_0.12 xtable_1.8-4 restfulr_0.0.15 pracma_2.4.2
[77] later_1.3.0 survival_3.5-5 tibble_3.2.1 iterators_1.0.14
[81] GenomicAlignments_1.34.1 memoise_2.0.1 cluster_2.1.4 ellipsis_0.3.2

**Comment by pradeep-sidd** [comment] 2023-03-29 18:12
I just saw an older thread with similar issue which was to be resolved by updating the package. I see that the package I installed is also outdated. i am trying to install the latest version using 'devtools::install_github("dami82/mutSignatures", force = TRUE, build_vignettes = TRUE)', but getting an error as below

── R CMD build ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\drpra\AppData\Local\Temp\RtmpGkJadt\remotesb0e861744a5a\dami82-mutSignatures-ad40601/DESCRIPTION' ...
─  preparing 'mutSignatures':
✔  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes (477ms)
E  creating vignettes (12.1s)
   --- re-building 'get_sarted_with_mutSignatures.Rmd' using rmarkdown
   Quitting from lines 15-34 (get_sarted_with_mutSignatures.Rmd) 
   Error: processing vignette 'get_sarted_with_mutSignatures.Rmd' failed with diagnostics:
   there is no package called 'kableExtra'
   --- failed re-building 'get_sarted_with_mutSignatures.Rmd'
   
   SUMMARY: processing the following file failed:
     'get_sarted_with_mutSignatures.Rmd'
   
   Error: Vignette re-building failed.
   Execution halted
Error: Failed to install 'mutSignatures' from GitHub:
  ! System command 'Rcmd.exe' failed

**Comment by pradeep-sidd** [comment] 2023-03-29 18:29
Sorry for the long thread. I installed the latest version of mutSignatures _2.1.5. But the error is persisting. Thanks for your patience.

Pradeep

**Comment by dami82** [comment] 2023-03-29 19:12
no worries.I just tested on a windows machine and completed the install succesfully. It appears you installed the dependencies but not the suggests (suggested packages). If you look at the line:Error: processing vignette 'get_sarted_with_mutSignatures.Rmd' failed with diagnostics:there is no package called 'kableExtra'--- failed re-building 'get_sarted_with_mutSignatures.Rmd'It clearly states that you don't have kableExtra installed. That is only used for the vignette (and is a super-common package), so you may have to install it if you want the vignette to be built. Additional suggests are dplyr, reshape2, gridExtra, knitr, rmarkdown. Alternatively, set build_vignette=FALSEBest regards,Damiano——Damiano FantiniSent from my iPhoneOn Mar 29, 2023, at 14:29, pradeep-sidd ***@***.***> wrote:﻿
Sorry for the long thread. I installed the latest version of mutSignatures _2.1.5. But the error is persisting. Thanks for your patience.
Pradeep

**Comment by pradeep-sidd** [comment] 2023-03-29 19:16
Thanks for the response, Damiano. I was able to install the latest mutSignatures package successfully, but the problem persists.

**Comment by dami82** [comment] 2023-03-29 19:20
can you provide a representative example? I have no idea what 'maf.dset.cholangio' is, so not sure how I can helpBest regards,Damiano——Damiano FantiniSent from my iPhoneOn Mar 29, 2023, at 13:34, pradeep-sidd ***@***.***> wrote:﻿
After multiple attempts, I installed the mutSignatures package and got it to work fine. However, in the middle of the code, I encountered an error while trying to attach the 3-nucleotide context. The message only mentioned that an error had occurred without any other information. I cannot make out where I faltered. I would really appreciate your perspective and help in this matter.
Command
Attach 3-nucleotide context
hg19 <- BSgenome.Hsapiens.UCSC.hg19::BSgenome.Hsapiens.UCSC.hg19
maf.dset.cholangio <- attachContext(mutData = maf.dset.cholangio,
chr_colName = "Chromosome",
start_colName = "Start_Position",
end_colName = "End_position",
nucl_contextN = 3,
BSGenomeDb = hg19)
An error has occurred!
Session info
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22621)
Matrix products: default
locale:
[1] LC_COLLATE=English_United States.utf8 LC_CTYPE=English_United States.utf8 LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C LC_TIME=English_United States.utf8
attached base packages:
[1] stats4 stats graphics grDevices utils datasets methods base
other attached packages:
[1] devtools_2.4.5 usethis_2.1.6 rlang_1.1.0
[4] maftools_2.14.0 mutSignatures_2.1.1 foreach_1.5.2
[7] ggplot2_3.4.1 BSgenome.Hsapiens.UCSC.hg19_1.4.3 BSgenome_1.66.3
[10] rtracklayer_1.58.0 Biostrings_2.66.0 XVector_0.38.0
[13] GenomicRanges_1.50.2 GenomeInfoDb_1.34.9 IRanges_2.32.0
[16] S4Vectors_0.36.2 BiocGenerics_0.44.0 BiocManager_1.30.20
loaded via a namespace (and not attached):
[1] bitops_1.0-7 matrixStats_0.63.0 fs_1.6.1 doParallel_1.0.17
[5] RColorBrewer_1.1-3 tools_4.2.2 profvis_0.3.7 utf8_1.2.3
[9] R6_2.5.1 colorspace_2.1-0 urlchecker_1.0.1 DNAcopy_1.72.3
[13] withr_2.5.0 tidyselect_1.2.0 prettyunits_1.1.1 processx_3.8.0
[17] compiler_4.2.2 cli_3.6.1 Biobase_2.58.0 DelayedArray_0.24.0
[21] scales_1.2.1 callr_3.7.3 proxy_0.4-27 stringr_1.5.0
[25] digest_0.6.31 Rsamtools_2.14.0 pkgconfig_2.0.3 htmltools_0.5.5
[29] sessioninfo_1.2.2 MatrixGenerics_1.10.0 fastmap_1.1.1 htmlwidgets_1.6.2
[33] rstudioapi_0.14 shiny_1.7.4 BiocIO_1.8.0 generics_0.1.3
[37] BiocParallel_1.32.6 dplyr_1.1.1 RCurl_1.98-1.12 magrittr_2.0.3
[41] GenomeInfoDbData_1.2.9 Matrix_1.5-3 Rcpp_1.0.10 munsell_0.5.0
[45] fansi_1.0.4 lifecycle_1.0.3 stringi_1.7.12 yaml_2.3.7
[49] SummarizedExperiment_1.28.0 zlibbioc_1.44.0 pkgbuild_1.4.0 grid_4.2.2
[53] parallel_4.2.2 promises_1.2.0.1 crayon_1.5.2 miniUI_0.1.1.1
[57] lattice_0.20-45 splines_4.2.2 ps_1.7.3 pillar_1.9.0
[61] rjson_0.2.21 codetools_0.2-19 pkgload_1.3.2 XML_3.99-0.14
[65] glue_1.6.2 data.table_1.14.8 remotes_2.4.2 vctrs_0.6.1
[69] httpuv_1.6.9 gtable_0.3.3 purrr_1.0.1 cachem_1.0.7
[73] mime_0.12 xtable_1.8-4 restfulr_0.0.15 pracma_2.4.2
[77] later_1.3.0 survival_3.5-5 tibble_3.2.1 iterators_1.0.14
[81] GenomicAlignments_1.34.1 memoise_2.0.1 cluster_2.1.4 ellipsis_0.3.2

**Comment by pradeep-sidd** [comment] 2023-03-29 19:24
I have attached the file I used. It is a TCGA data set on cholangiocarcinoma. 

[cholangio.cna.clinical_maftools.zip](https://github.com/dami82/mutSignatures/files/11104763/cholangio.cna.clinical_maftools.zip)

Best

Pradeep

**Comment by dami82** [comment] 2023-03-29 20:20
Thanks. Before I look into this, make sure that seqNames in the MAF file are consistent with the BSgenome object you are using. I think MAF files from TCGA typically use 1, 2, 3 as chromosome names.. on the contrary, your hg19 object should have chr1, chr2, chr3...If so, please mutate your chromosome_name column in your maf data.frame to match what you have in hg19.This should be a piece of cake if you use paste0 and mutate. x=x %>% mutate(chrom_name = paste0('chr', .$chrom_name)) and then re run. I hope this is helpful.Best regards,Damiano——Damiano FantiniSent from my iPhoneOn Mar 29, 2023, at 15:24, pradeep-sidd ***@***.***> wrote:﻿
I have attached the file I used. It is a TCGA data set on cholangiocarcinoma.
cholangio.cna.clinical_maftools.zip
Best
Pradeep

**Comment by pradeep-sidd** [comment] 2023-03-29 20:46
Thank you so much for your suggestion. Indeed the chromosome numbers were depicted different in the 2 onjects. I made the changes as  suggested, despite which I am getting the same error message.

Best

Pradeep

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by dami82** [comment] 2023-03-29 21:08
ok, then I'll try to run the data you sent me through the pipeline and see what is happening. Give me 1-2 days.Best regards,Damiano——Damiano FantiniSent from my iPhoneOn Mar 29, 2023, at 16:46, pradeep-sidd ***@***.***> wrote:﻿
Thank you so much for your suggestion. Indeed the chromosome numbers were depicted different in the 2 onjects. I made the changes as  suggested, despite which I am getting the same error message.



Best



Pradeep



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows



From: Damiano ***@***.***>

Sent: Wednesday, March 29, 2023 1:20 PM

To: ***@***.***>

Cc: ***@***.***>; ***@***.***>

Subject: Re: [dami82/mutSignatures] mutSignatures package: error after importing data from MAF files (Issue #19)



Thanks. Before I look into this, make sure that seqNames in the MAF file are consistent with the BSgenome object you are using. I think MAF files from TCGA typically use 1, 2, 3 as chromosome names.. on the contrary, your hg19 object should have chr1, chr2, chr3...If so, please mutate your chromosome_name column in your maf data.frame to match what you have in hg19.This should be a piece of cake if you use paste0 and mutate. x=x %>% mutate(chrom_name = paste0('chr', .$chrom_name)) and then re run. I hope this is helpful.Best regards,Damiano——Damiano FantiniSent from my iPhoneOn Mar 29, 2023, at 15:24, pradeep-sidd ***@***.***> wrote:﻿

I have attached the file I used. It is a TCGA data set on cholangiocarcinoma.

cholangio.cna.clinical_maftools.zip

Best

Pradeep

**Comment by pradeep-sidd** [comment] 2023-03-29 21:10
Thank you for your help. I will wait for your response.

Pradeep

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dami82** [comment] 2023-04-02 22:24
Hello Pradeep. I had a closer look at your query. 
Unfortunately, I could NOT reproduce your error. I analyzed the file you provided via the standard `mutSignatures` pipeline and obtained the expected results. This is great news. Now, about what you need to do to fix the issue you ran into... I identified a few possible explanations:
- make sure to run all pre-processing steps. If you are skipping the initial filtering steps, you may run into issues. Please, see the attached PDF file as well as the package vignette.
- system-specific issues. I do not work with Windows OS and hence I cannot troubleshoot errors that are Win-specific. I ran all my tests in linux and everything worked perfectly. If you keep running into errors, I would strongly recommend using Linux or Unix for your analyses
- Resources. Make sure you have sufficient memory to perform the tasks at hand: I would recommend at least 8 cores and 16Gb memory.  

Here, I attach a vignette with all the code I used to analyze your MAF file. I hope you'll find this useful. I am closing this thread cause your issue is NOT due to a problem in the `mutSignatures` code. 
Best regards.
 
[MAF_pipeline_standard.pdf](https://github.com/dami82/mutSignatures/files/11133484/MAF_pipeline_standard.pdf)

**Closed as completed by dami82** 2023-04-02 22:24 UTC

**Comment by pradeep-sidd** [comment] 2023-04-04 12:11
Thank you so much. Will review it and get back to you.

Best

Pradeep

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
